version: '2'

services:
  postgres:
    restart: always
    env_file:
      - env
    image: postgres:latest
    volumes_from:
      - data
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./backups/postgresql:/backup
    expose:
      - "5432"
      
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6379"

  web:
    restart: always
    env_file:
      - env
    depends_on:
      - postgres
      - redis
    build: ./web/
    expose:
      - "8000"
    links:
      - postgres:postgres
      - redis:redis
    working_dir: /data/web/applab
    volumes:
      - ./web:/data/web
    command: /usr/bin/gunicorn applab.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes_from:
      - web
    links:
      - web:web

  data:
    restart: always
    image: alpine
    volumes:
      - /var/lib/postgresql
    command: "true"
